import { AppConfig } from '../types';

export function generateGitHubWorkflowYaml(config: AppConfig): string {
  const sanitizeName = (name: string) => name.toLowerCase().replace(/[^a-z0-9]/g, '-');
  const appSlug = sanitizeName(config.appName || 'my-web-app');

  const permissionsList: string[] = [];
  if (config.permissions.internet) permissionsList.push('android.permission.INTERNET');
  if (config.permissions.notifications) permissionsList.push('android.permission.POST_NOTIFICATIONS');
  if (config.permissions.fileUpload) permissionsList.push('android.permission.READ_EXTERNAL_STORAGE', 'android.permission.WRITE_EXTERNAL_STORAGE');
  if (config.permissions.cameraAccess) permissionsList.push('android.permission.CAMERA');
  if (config.permissions.microphoneAccess) permissionsList.push('android.permission.RECORD_AUDIO');
  if (config.permissions.keepScreenOn) permissionsList.push('android.permission.WAKE_LOCK');

  return `# GitHub Actions Workflow generated by APK Builder
# Place this file at .github/workflows/build-apk.yml in your repository

name: Build Android APK (${config.appName || 'Web App'})

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      version_name:
        description: 'Version Name'
        required: false
        default: '${config.versionName || '1.0.0'}'

jobs:
  build-apk:
    name: Build & Release APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Configure Webview APK Settings
        run: |
          echo "Building APK for ${config.appName || 'Web App'}"
          echo "Web App URL: ${config.webAppUrl || 'https://example.com'}"
          echo "Package ID: ${config.packageName || 'com.example.app'}"
          echo "Version: ${config.versionName || '1.0.0'} (${config.versionCode || 1})"

      - name: Generate Android Manifest & Gradle Config
        run: |
          mkdir -p android/app/src/main
          cat << 'EOF' > android/app/src/main/AndroidManifest.xml
          <?xml version="1.0" encoding="utf-8"?>
          <manifest xmlns:android="http://schemas.android.com/apk/res/android"
              package="${config.packageName || 'com.company.app'}">

              ${permissionsList.map(p => `<uses-permission android:name="${p}" />`).join('\n              ')}

              <application
                  android:allowBackup="true"
                  android:icon="@mipmap/ic_launcher"
                  android:label="${config.appName || 'Web App'}"
                  android:roundIcon="@mipmap/ic_launcher_round"
                  android:supportsRtl="true"
                  android:theme="@style/Theme.AppCompat.Light.NoActionBar">
                  <activity
                      android:name=".MainActivity"
                      android:exported="true"
                      android:screenOrientation="${config.orientation}"
                      android:configChanges="orientation|keyboardHidden|screenSize">
                      <intent-filter>
                          <action android:name="android.intent.action.MAIN" />
                          <category android:name="android.intent.category.LAUNCHER" />
                      </intent-filter>
                  </activity>
              </application>
          </manifest>
          EOF

      - name: Build Debug APK
        run: |
          cd android
          chmod +x gradlew || true
          # Simulating Gradle build command:
          # ./gradlew assembleDebug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${appSlug}-v${config.versionName || '1.0.0'}-apk
          path: |
            android/app/build/outputs/apk/debug/app-debug.apk
            android/app/build/outputs/apk/release/app-release-unsigned.apk
          retention-days: 14
`;
}

export function generateBuildConfigJson(config: AppConfig): string {
  return JSON.stringify(config, null, 2);
}
